name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run FastAPI App
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: Install Zrok
        run: |
          curl -fsSL https://get.openziti.io/zrok | bash
          sudo mv zrok /usr/local/bin/

      - name: Start Zrok Tunnel
        run: |
          zrok enable --token DoqCtBqwExoZ
          zrok share http 8000
